#!/usr/bin/env bash

# configuring external workspace
external/start console cmd rm -rf "$CONTECO_REALM"
external/start console load vcwebio/conteco.backup.external
external/start console extract vcwebio/conteco.backup.external
external/start console restore external
external/start repo remove backup.external
external/start repo load .
external/start repo retag-image "${INFOMETIS_REGISTRY}${INFOMETIS_REALM}" .
external/start console cmd chmod -R 777 "$CONTECO_REALM"
external/start console cmd mkdir "${INFOMETIS_REALM}"
external/start console cmd cp -r "${CONTECO_REALM}/*" "${INFOMETIS_REALM}"
external/start console cmd chmod -R 777 "${INFOMETIS_REALM}"
if [[ "${INFOMETIS_REGISTRY_RUNNING}" == "true" ]] ; then
  external/start "--registry=${INFOMETIS_REGISTRY}" "--realm=${INFOMETIS_REALM}" release .
fi
