##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS wrapper
FROM vcwebio/conteco.external.controlplane AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image.base/Dockerfile/conteco #####
COPY --from=wrapper /conteco/ /conteco/
ENTRYPOINT ["/conteco/bin/image/wrapper/entrypoint"]
##### END image.base/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV CONTECO_ENTRYPOINT="check-extract-cli" \
    CONTECO_PREENTRYPOINT="/conteco/bin/controlplane/internal/entrypoint"
WORKDIR /conteco/pwd
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="controlplane" \
    CONTECO_NAME="cli" \
    CONTECO_TAG="v1.1.0" \
    CONTECO_BASE="external.controlplane" \
    CONTECO_BUILD="image-base" \
    CONTECO_LABELSPACE="io.vcweb"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="controlplane" \
      io.vcweb.name="cli" \
      io.vcweb.tag="v1.1.0" \
      io.vcweb.base="external.controlplane" \
      io.vcweb.build="image-base" \
      io.vcweb.label="controlplane.cli - Conteco" \
      io.vcweb.description="The Conteco controlplane commandline interface image." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.controlplane.cli --help"
##### END image.base/Dockerfile/env-labels-footer #####
