#!/usr/bin/env bash

export CONTECO_LABEL="controlplane.cli - Conteco"
export CONTECO_DESCRIPTION="The Conteco controlplane commandline interface image."

export CONTECO_TYPE="controlplane"
export CONTECO_NAME="cli"
export CONTECO_TAG="v1.0.5"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="external.controlplane"
export CONTECO_BUILD="image-base"
